variables:
  - pkg_name: node
  - pkg_ver: '6.11.0'

revision: 1

# Dependencies
dependencies:
    musl-libc:
        - headers
        - libs
    libcxx-4.0:
        - headers
        - libs
    openssl-1.0:
        - rt

prepare:
  - apk add linux-headers python2

# Source
source:
  tar.gz: https://nodejs.org/dist/v{pkg_ver}/{pkg_name}-v{pkg_ver}.tar.gz

resources:
  - common.gypi

# Build stage
build:
  # Patch common.gypi for rdynamic flag
  - cp ../common.gypi ./
  - CC=gclang
    CXX=gclang++
    ./configure
    --fully-static
    --enable-static
    --openssl-no-asm
    --with-intl=small-icu
  - make -j{__NB_CORES__}
  - make DESTDIR={__INSTALL_DIR__} install
