variables:
  - pkg_name: node
  - pkg_ver: '6.11.0'

# Dependencies
dependencies:
    musl-libc:
        - headers
        - libs
    libcxx-4.0:
        - headers
        - libs
    zlib-1.2:
        - headers
        - libs
    libuv-1.11:
        - headers
        - libs

prepare:
  - apk add linux-headers python2

# Source
source:
  tar.gz: https://nodejs.org/dist/v{pkg_ver}/{pkg_name}-v{pkg_ver}.tar.gz

resources:
  - common.gypi

# Build stage
build:
  # Patch common.gypi for rdynamic flag
  - cp ../common.gypi ./
  - WLLVM_CONFIGURE_ONLY=1
    CC=gclang
    CXX=gclang++
    ./configure
    --prefix={__INSTALL_DIR__}
    --fully-static
    --shared-libuv
    --shared-zlib
    --with-intl=full-icu
    --download=all
  - make -j{__NB_CORES__}
  - make install
