variables:
  - pkg_name: nginx
  - pkg_ver: '1.12.0'

revision: 1

# Dependencies
dependencies:
  musl-libc:
    - headers
    - libs
  zlib-1.2:
    - headers
    - libs
  openssl-1.0:
    - headers
    - libs
  pcre-8.40:
    - headers
    - libs

prepare:
  - apk add linux-headers

# Source
source:
  tar.gz: http://nginx.org/download/{pkg_name}-{pkg_ver}.tar.gz

# Build stage
build:
  - GLLVM_CONFIGURE_ONLY=1
    CC=gclang ./configure
    --prefix={__INSTALL_DIR__}
    --sbin-path={__INSTALL_DIR__}/bin/nginx
    --error-log-path=/var/log/nginx/error.log
    --http-log-path=/var/log/nginx/access.log
    --pid-path=/var/run/nginx.pid
    --lock-path=/var/run/nginx.lock
    --http-client-body-temp-path=/var/cache/nginx/client_temp
    --http-proxy-temp-path=/var/cache/nginx/proxy_temp
    --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp
    --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp
    --http-scgi-temp-path=/var/cache/nginx/scgi_temp
    --user=nginx
    --group=nginx
    --with-cc-opt="-static -Wno-sign-compare"
    --with-ld-opt="-static" --with-cpu-opt=generic --with-pcre
    --with-mail --with-poll_module --with-select_module
    --with-http_ssl_module
    --with-http_gzip_static_module --with-http_auth_request_module
    --with-http_random_index_module --with-http_secure_link_module
    --with-http_degradation_module --with-http_stub_status_module
    --with-mail --with-mail_ssl_module
  - make
  - make install
