release_date: 2017-07-18

variables:
  - pkg_name: readline
  - pkg_ver: '7.0'

# Dependencies
dependencies:
  musl-libc:
    - headers
    - libs
  ncurses-6.0:
    - headers

# Source
source:
  tar.gz: ftp://ftp.cwru.edu/pub/bash/{pkg_name}-{pkg_ver}.tar.gz

# Build stage
build:
  - WLLVM_CONFIGURE_ONLY=1
    CC=gclang
    ./configure
    --prefix={__INSTALL_DIR__}
    --enable-shared=no
  - make
  - make install
