variables:
  - pkg_name: gdbm
  - pkg_ver: '1.13'

revision: 1

# Dependencies
dependencies:
  musl-libc:
    - headers
    - libs

# Source
source:
  tar.gz: ftp://ftp.gnu.org/gnu/{pkg_name}/{pkg_name}-{pkg_ver}.tar.gz

# Build stage
build:
  - GLLVM_CONFIGURE_ONLY=1
    CC=gclang
    ./configure
    --prefix={__INSTALL_DIR__}
    --enable-shared=no
    --enable-libgdbm-compat
    CFLAGS="-static"
    LDFLAGS="-static"
  - make
  - make install
  - mkdir -p {__INSTALL_DIR__}/include/gdbm
  - cp compat/ndbm.h {__INSTALL_DIR__}/include/gdbm
