variables:
  - pkg_name: ncurses
  - pkg_ver: '6.0'

revision: 1

# Dependencies
dependencies:
  musl-libc:
    - headers
    - libs

# Source
source:
  tar.gz: https://ftp.gnu.org/gnu/{pkg_name}/{pkg_name}-{pkg_ver}.tar.gz

# Build stage
build:
  - WLLVM_CONFIGURE_ONLY=1
    CC=gclang
    ./configure --prefix={__INSTALL_DIR__}
  - make LDFLAGS="-static"
  - make install
