variables:
  - pkg_name: zlib
  - pkg_ver: '1.2.11'

# Dependencies
dependencies:
  musl-libc:
    - headers
    - libs

# Source
source:
  tar.gz: http://zlib.net/{pkg_name}-{pkg_ver}.tar.gz

# Build stage
build:
  - WLLVM_CONFIGURE_ONLY=1
    CC=gclang
    CFLAGS="-static"
    ./configure
    --prefix={__INSTALL_DIR__}
    --static
  - make
  - make install
